name: CI - Static Analysis & Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run flake8
      run: |
        flake8 || (echo "flake8 found issues" && exit 1)
    - name: Run bandit
      run: |
        bandit -r . -n 5 -lll || (echo "bandit found issues" && exit 1)
    - name: Run tests
      run: |
        pytest -q
