name: Security Scan CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      # 4. Run Flake8
      - name: Run Flake8
        run: |
          echo "### Flake8 Output ###"
          flake8 . || true

      # 5. Run Bandit
      - name: Run Bandit
        run: |
          echo "### Bandit Output ###"
          bandit -r . -f cli || true
