name: Security Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11  # Change from 3.1 to 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 bandit

    - name: Run Flake8
      run: |
        echo "### Flake8 Output ###"
        flake8 . || true

    - name: Run Bandit
      run: |
        echo "### Bandit Output ###"
        bandit -r . || true
