name: security_scan

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 bandit

      - name: Run Flake8
        run: |
          echo "### Flake8 Output ###"
          flake8 --exclude=venv,venv311,uploads

      - name: Run Bandit
        run: |
          echo "### Bandit Output ###"
          bandit -r . -x venv,venv311,uploads -f json -o bandit_report.json
          cat bandit_report.json
